export const COUNTER_INCREASE = "COUNTER_INCREASE";
export const COUNTER_DECREASE = "COUNTER_DECREASE";
export const COUNTER_RESET = "COUNTER_RESET";
export const PONG_RESPONSE = "PONG_RESPONSE";
export const PONG_ERROR = "PONG_ERROR";
export const RESET_PING = "RESET_PING";
